# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'explanation.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExplanationWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 634)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 10, 571, 211))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 220, 571, 181))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, 400, 571, 181))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(570, 10, 471, 91))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(570, 100, 471, 111))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(570, 400, 471, 181))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(570, 210, 471, 191))
        self.textBrowser_6.setObjectName("textBrowser_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:10pt; color:#333333; background-color:#ffffff;\">The Sleeping Barber problem is an inter-process communication and synchronization problem. The original variation of the problem is attributed to </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:10pt; font-style:italic; color:#333333; background-color:#ffffff;\">Dijkstra</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:10pt; color:#333333; background-color:#ffffff;\">, but we will work with the following variation:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:10pt; color:#333333;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:10pt; color:#333333; background-color:#ffffff;\">A barbershop consists of a waiting room with n chairs, and the barber room containing the barber chair. If there are no customers to be served, the barber goes to sleep. If a customer enters the barbershop and all chairs are occupied, then the customer leaves the shop. If the barber is busy, but chairs are available, then the customer sits in one of the free chairs. If the barber is asleep, the customer wakes up the barber.</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">Another way to look at the Sleeping Barber Problem is to think of the Producer-Consumer problem, except that the roles of Producer and Consumer are not analogous to the usual business point of view where usually the Producer would be the barber and the Consumer would be the customer.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">Customers are</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\"> </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:696; color:#333333;\">produced</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\"> when they come to the barbershop, and barbers </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:696; color:#333333;\">consume</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\"> the customers when they give them haircuts.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">Some concepts are vital to keep in mind before proposing a solution to this problem, such as</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\"> </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:696; color:#333333;\">race conditions</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\">.</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<h4 style=\" margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:110%; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:496; color:#333333; background-color:#ffffff;\">Race Conditions</span></h4>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">Processes or threads that are working together may share common storage that is used to read and write, whether it is located in memory or in a shared file. Race conditions are situations where the final result of an operation on the shared data depends on which process or thread runs precisely when.</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:10pt; color:#333333; background-color:#ffffff;\">Avoiding </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:696; color:#333333; background-color:#ffffff;\">race conditions</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\"> requires that read and write operations on shared data are never done at the same time when executed by more than one process or thread simultaneously. Which brings us to another important concept, </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:696; color:#333333; background-color:#ffffff;\">mutual exclusion</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">.</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<h4 style=\" margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:110%; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:496; color:#333333; background-color:#ffffff;\">Mutual Exclusion</span></h4>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">Ensuring that while one process or thread is performing read or write operations on shared data others are prohibited of doing the same.</span></p></body></html>"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "1. No two or more can be simultaneously inside their critical region.\n"
""))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "2. No assumptions may be made about number of CPUs or speed.\n"
""))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "3. No blocking others while outside the critical region.\n"
""))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "4. It should not take long to enter the critical region.\n"
""))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:10pt; color:#333333; background-color:#ffffff;\">Processes and threads aren\'t always executing operations that might lead to race conditions, part of the time they are running internal computations outside of their </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:10pt; font-weight:696; color:#333333; background-color:#ffffff;\">critical region</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:10pt; color:#333333; background-color:#ffffff;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:10pt; color:#333333;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:10pt; color:#333333; background-color:#ffffff;\">To have processes or threads running in parallel and cooperating efficiently while using shared data, we need the following four conditions to be satisfied.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ExplanationWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
