# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solution.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Solution(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1063, 862)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 411, 141))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 140, 411, 181))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, 320, 411, 261))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(410, 0, 571, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(410, 30, 641, 161))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(410, 190, 641, 151))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(410, 340, 641, 151))
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(410, 470, 641, 351))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(0, 580, 411, 51))
        self.textBrowser_7.setObjectName("textBrowser_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1063, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">After understanding the Sleeping Barber Problem and the core concepts behind the real problems of running asynchronous operations on shared data, we can start to work out a solution.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">As in many other problems in various domains of computing, there are more than one possible solutions to the problem. We will be analyzing one that involves two thread synchronization mechanisms:</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\"> </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:696; color:#333333;\">semaphores</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\"> and </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:696; color:#333333;\">mutexes</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\">.</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<h4 style=\" margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:110%; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:496; color:#333333; background-color:#ffffff;\">Semaphores</span></h4>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">A type of variable that counts the number of wakeups saved for future use.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:496; color:#333333; background-color:#ffffff;\">Mutexes</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">A simplified version of a semaphore used when the semaphores\' ability to count and save wakeups is not needed. Mutexes are generally used to manage mutual exclusion, having only two states: locked or unlocked.</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-style:italic; color:#333333;\">Dijkstra</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\"> proposed that semaphores have two operations: </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:696; color:#333333;\">down </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\">and </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:696; color:#333333;\">up</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">The down operation checks if the value of a semaphore is greater than 0. If it is, one wakeup saved in the semaphore is used and the process or thread proceeds. However, if the value is 0, the process or thread is put to sleep without completing the down operation. Checking the value on a semaphore and changing it or going to sleep is a single</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\"> </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:696; color:#333333;\">atomic action</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">The up operation adds one wakeup to the semaphore. If one or more processes or threads were sleeping due to a down operation on that semaphore, one will be chosen arbitrarily by the system and will complete its down operation and proceed. This is also an atomic action.</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Solution</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">For our implementation, we will be using two semaphores and one mutex. One of the semaphores will be for the customers in the waiting room and the other one will be for the barber. The mutex will be used for mutual exclusion.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">Aside from that, we will need to define the number of chairs in the waiting room, which will be our limit on the number of customers and keep a control variable of the number of customers currently waiting.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">From the description of the problem, we have that the customer will either get a haircut or leave the barbershop; the barber can only cut hair. Those three actions will be our functions.</span></p></body></html>"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Barber"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Sleeps if no one\'s waiting.\n"
""))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Brings one customer to the barber\'s chair.\n"
""))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "Cuts the customer\'s hair.\n"
""))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "Customer"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "Leaves if barbershop is full, waits otherwise.\n"
""))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "Sits in the barber\'s chair.\n"
""))
        item = self.listWidget_2.item(3)
        item.setText(_translate("MainWindow", "Cuts the customer\'s hair\n"
""))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">The barber has only three actions, repeated until he closes the shop. Let\'s analyze each one.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">To check for a client, sleep if no one\'s waiting and wake up when a customer arrives, we run a down operation on the customers semaphore. When a customer arrives, the barber brings them to the barber\'s chair,</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\"> </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:696; color:#333333;\">and then there is one less customer in the waiting room</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\">. Now the barber is ready to work. After the hair cut, the barber checks for a client and the cycle repeats.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">The customer also has three actions but, unlike the barber, the customer only performs his actions once.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">When a customer arrives, he</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\"> </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:696; color:#333333;\">checks to see if there\'s a chair available in the waiting room</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\">. If there isn\'t, the customer leaves. Otherwise the customer waits, </span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; font-weight:696; color:#333333;\">and the number of customers in the waiting room increases</span><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333;\">. To wakeup the sleeping barber, the customer runs an up on the customers semaphore, and then a down on the barber semaphore, waiting to be brought to the barber\'s chair.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">That is the main part of our solution, but we didn\'t deal with the mutex for the possible race condition. The critical region is the highlighted part in both role descriptions, where they read and write from the variable that keeps count of the number of customers waiting.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Helvetica Neue\',\'Helvetica\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">After wrapping the highlighted parts in both the customer and the barber with the mutex, the problem is solved!</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Concepts</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Solution()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
